# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/matheus/TCC/layout/tcc.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(840, 460)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(600, 10, 231, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 141, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 171, 17))
        self.label_3.setObjectName("label_3")
        self.labelBacklashEstimado = QtWidgets.QLabel(self.frame)
        self.labelBacklashEstimado.setGeometry(QtCore.QRect(10, 110, 211, 20))
        self.labelBacklashEstimado.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelBacklashEstimado.setObjectName("labelBacklashEstimado")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 150, 67, 17))
        self.label_4.setObjectName("label_4")
        self.dial = QtWidgets.QDial(self.frame)
        self.dial.setGeometry(QtCore.QRect(20, 160, 50, 64))
        self.dial.setMaximum(100)
        self.dial.setObjectName("dial")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 16, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(70, 200, 21, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(0, 250, 201, 17))
        self.label_7.setObjectName("label_7")
        self.checkBoxRNA = QtWidgets.QCheckBox(self.frame)
        self.checkBoxRNA.setGeometry(QtCore.QRect(10, 280, 201, 23))
        self.checkBoxRNA.setObjectName("checkBoxRNA")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 380, 67, 17))
        self.label_8.setObjectName("label_8")
        self.btnGravar = QtWidgets.QPushButton(self.frame)
        self.btnGravar.setGeometry(QtCore.QRect(10, 410, 89, 25))
        self.btnGravar.setObjectName("btnGravar")
        self.btnPararGravar = QtWidgets.QPushButton(self.frame)
        self.btnPararGravar.setGeometry(QtCore.QRect(130, 410, 89, 25))
        self.btnPararGravar.setObjectName("btnPararGravar")
        self.checkBoxMalha = QtWidgets.QCheckBox(self.frame)
        self.checkBoxMalha.setGeometry(QtCore.QRect(10, 310, 201, 23))
        self.checkBoxMalha.setObjectName("checkBoxMalha")
        self.btnBacklashUp = QtWidgets.QPushButton(self.frame)
        self.btnBacklashUp.setGeometry(QtCore.QRect(150, 50, 31, 25))
        self.btnBacklashUp.setObjectName("btnBacklashUp")
        self.btnBacklashDown = QtWidgets.QPushButton(self.frame)
        self.btnBacklashDown.setGeometry(QtCore.QRect(190, 50, 31, 25))
        self.btnBacklashDown.setObjectName("btnBacklashDown")
        self.labelReferencia = QtWidgets.QLabel(self.frame)
        self.labelReferencia.setGeometry(QtCore.QRect(100, 180, 121, 20))
        self.labelReferencia.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelReferencia.setObjectName("labelReferencia")
        self.MplWidget = Mplwidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(10, 10, 571, 441))
        self.MplWidget.setObjectName("MplWidget")
        #mainWindow.setCentralWidget(self.centralwidget)
        self.actionControlador = QtWidgets.QAction(mainWindow)
        self.actionControlador.setObjectName("actionControlador")
        self.actionRede_neural = QtWidgets.QAction(mainWindow)
        self.actionRede_neural.setObjectName("actionRede_neural")

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "TCC"))
        self.label.setText(_translate("mainWindow", "Configurar:"))
        self.label_2.setText(_translate("mainWindow", "Espaçamento (mm):"))
        self.label_3.setText(_translate("mainWindow", "Backlash estimado (rad): "))
        self.labelBacklashEstimado.setText(_translate("mainWindow", "0"))
        self.label_4.setText(_translate("mainWindow", "Setpoint:"))
        self.label_5.setText(_translate("mainWindow", "0"))
        self.label_6.setText(_translate("mainWindow", "2π"))
        self.label_7.setText(_translate("mainWindow", "Controle:"))
        self.checkBoxRNA.setText(_translate("mainWindow", "Ativar compensador (RNA)"))
        self.label_8.setText(_translate("mainWindow", "Salvar:"))
        self.btnGravar.setText(_translate("mainWindow", "Gravar"))
        self.btnPararGravar.setText(_translate("mainWindow", "Parar"))
        self.checkBoxMalha.setText(_translate("mainWindow", "Fechar malha"))
        self.btnBacklashUp.setText(_translate("mainWindow", "+"))
        self.btnBacklashDown.setText(_translate("mainWindow", "-"))
        self.labelReferencia.setText(_translate("mainWindow", "0"))
        self.actionControlador.setText(_translate("mainWindow", "Controlador"))
        self.actionRede_neural.setText(_translate("mainWindow", "Rede neural"))

from mplwidget import Mplwidget
